@startuml

class Entity {
    +int Id : "egyedi azonosító"
    +DateTime CreatedAt : "készítés dátum"
    +DateTime UpdatedAt : "utolsó frissítés dátum"
}

class Review {
    +Student Student : "véleményt író diák"
    +TeacherSubjectAtSchool TeacherSubjectAtSchool : "tanár és a tanított tárgy az iskolában"
    +string Content : "tartalom"
    +int Rating : "értékelés (1-5)"
}

Entity <|-- Review

@enduml