# Generated by Django 5.1.1 on 2024-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default=1, help_text='Az e-mail cím egyedinek kell lennie.', max_length=254, unique=True, verbose_name='E-mail cím'),
            preserve_default=False,
        ),
    ]
