# Generated by Django 5.1.1 on 2024-09-25 12:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_teacher_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='Születési dátum'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to='auth.group', verbose_name='Csoportok'),
        ),
        migrations.AlterField(
            model_name='student',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviewed_students', to='core.review', verbose_name='Értékelések'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(verbose_name='Születési dátum'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(help_text='Az e-mail címnek egyedinek kell lennie.', max_length=254, unique=True, verbose_name='E-mail cím'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Keresztnév'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Vezetéknév'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviewed_teachers', to='core.review', verbose_name='Értékelések'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_teachers', to='core.school', verbose_name='Iskola'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(choices=[('Mr', 'Úr'), ('Mrs', 'Asszony'), ('Miss', 'Hölgy'), ('Dr', 'Dr,'), ('Prof', 'Prof.')], default='Mr', max_length=10, verbose_name='Megnevezés'),
        ),
    ]
